USE BANCO ;

CREATE TABLE CLIENTES (
ID_CLIENTE INT IDENTITY (1,1) PRIMARY KEY,
NOMBRES VARCHAR (20) NOT NULL , 
APELLIDOS VARCHAR (20) NOT NULL,
SEXO CHAR(1) NOT NULL CHECK (SEXO IN ('M','F' )),
FECHA_NAC DATE NOT NULL,
CIUDAD VARCHAR (100) NOT NULL,
FECHA_REGISTRO DATE NOT NULL,
);
GO

SELECT * FROM CLIENTES


CREATE TABLE SUCURSALES (
ID_SUCURSALES INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_SUCURSAL VARCHAR (150) NOT NULL,
CIUDAD_SUCURSAL VARCHAR (200) NOT NULL

); 

GO

SELECT * FROM SUCURSALES

CREATE TABLE TIPOS_DE_CUENTAS (
ID_TIPO_DE_CUENTAS INT IDENTITY (1,1) PRIMARY KEY,
NOMBRE_TIPO_DE_CUENTAS VARCHAR (100) NOT NULL 
);
GO



SELECT * FROM TIPOS_DE_CUENTAS

CREATE TABLE CUENTAS (
ID_CUENTA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
ID_CLIENTE INT NOT NULL ,
ID_SUCURSALES INT NOT NULL,
ID_TIPO_DE_CUENTAS INT NOT NULL,
SALDO DECIMAL (18,2) NOT NULL,
FECHA_APERTURA DATE NOT NULL ,

CONSTRAINT FK_CUENTAS_CLIENTES
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTES(ID_CLIENTE), 


CONSTRAINT FK_CUENTAS_SUCURSALES
FOREIGN KEY (ID_SUCURSALES)
REFERENCES SUCURSALES(ID_SUCURSALES),


CONSTRAINT FK_CUENTAS_TIPOS_CUENTAS
FOREIGN KEY (ID_TIPO_DE_CUENTAS)
REFERENCES TIPOS_DE_CUENTAS(ID_TIPO_DE_CUENTAS),

); 

GO

CREATE TABLE PRESTAMOS (
ID_PRESTAMO INT IDENTITY(1,1) PRIMARY KEY ,
ID_CLIENTE INT NOT NULL,
MONTO DECIMAL (18,2) NOT NULL,
TAZA_INTERES DECIMAL (5,2) NOT NULL , 
PLAZO_MESES INT NOT NULL,
ESTADO VARCHAR (20) NOT NULL,
FECHA_OTORGAMIENTO DATE NOT NULL,

CONSTRAINT FK_PRESTAMOS_CLIENTES
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTES(ID_CLIENTE)

);
GO



CREATE TABLE TRANSACCIONES
(
    ID_TRANSACCION INT IDENTITY(1,1) PRIMARY KEY,

    ID_CUENTA INT NOT NULL,

    FECHA DATETIME NOT NULL,

    TIPO VARCHAR(20) NOT NULL,

    MONTO DECIMAL(18,2) NOT NULL,

    DESCRIPCION VARCHAR(200),

    CONSTRAINT FK_TRANSACCIONES_CUENTAS
        FOREIGN KEY(ID_CUENTA)
        REFERENCES CUENTAS(ID_CUENTA)
);
GO


SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE';

/*
¿Por qué Cuentas tiene id_cliente y no nombre_cliente?

¿Qué pasaría si intentaras crear una cuenta con id_cliente = 9999 y ese cliente no existe?

¿Por qué usamos IDENTITY(1,1) en lugar de escribir los IDs manualmente?
*/
