USE BANCO ;
GO

SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE';
GO


--OBTENER INFORMACION DE UNA TABLA EJEMPLO : 'CLIENTES'
SELECT * FROM CLIENTES;
GO

--MOSTRAR SOLO ALGUNAS COLUMNAS DE CLIENTES : NOMBRE Y APELLIDO.

SELECT NOMBRES, APELLIDOS FROM CLIENTES;
GO

--CAMBIAR EL NOMBRE DE LA COLUMNA APELLIDO QUE ESTA EN PLURAL , DEJARLOS SINGULAR DE LA TABLA CLIENTES
SELECT APELLIDOS AS APELLIDO FROM CLIENTES;
GO

--	FILTRAR REGISTROS , SOLO DE MANAGUA.
SELECT * FROM CLIENTES
WHERE CIUDAD = 'MANAGUA' ;
GO
--FILTRO DE SEXO , SOLO HOMBRES
SELECT * FROM CLIENTES
WHERE SEXO = 'M';
GO

--CLIENTES REGISTRADOS DESPUES DEL 1 DE ENERO DEL 2009
SELECT * FROM CLIENTES 
WHERE FECHA_REGISTRO >= '2015';
GO






SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE';
GO
--ORDER BY (ORDENAR INFORMACION)

--ORDENAR SALDO DEL CLIENTE , MAYOR A MENOR
SELECT * FROM CUENTAS
ORDER BY SALDO DESC ;
GO
--SALDO DEL CLIENTE , MENOR PRIMERO A MAYOR
SELECT * FROM CUENTAS
ORDER BY SALDO ASC ;


-- ORDENAR ALFABETICAMENTE 
 SELECT * FROM CLIENTES
 ORDER BY NOMBRES;
 GO

 --MOSTRAR UNICAMENTE LOS 3 PRIMEROS CLIENTES
 SELECT TOP 3 *
 FROM CLIENTES ;
 GO

 --LOS DOS SALDOS MAS ALTOS DE CUENTAS
 SELECT  TOP 2 *
 FROM CUENTAS 
 ORDER BY SALDO DESC ;
 GO

 --LOS DOS SALDOS MAS BAJOS DE CUENTAS
 SELECT TOP 2 *
 FROM CUENTAS
 ORDER BY SALDO ASC;
 GO

 --ELIMINAR LOS REPETIDOS DE LAS CIUDADES USANDO DISTINT
 SELECT 
 DISTINCT CIUDAD
 FROM CLIENTES;
 GO	

 --CUANTOS CLIENTES TENEMOS
 SELECT COUNT(*) AS TOTAL_DE_LOS_CLIENTES
 
 FROM CLIENTES;
 GO 

 -- CUANTAS CUENTAS EXISTEN
 SELECT COUNT(*) TOTAL_DE_CUENTAS
 FROM CUENTAS;
 GO

 --SALDO TOTAL DEL BANCO 
 SELECT * FROM CUENTAS
 SELECT SUM(SALDO) AS TOTAL_DEL_SALDO_BANCARIO
 FROM CUENTAS;
 GO

 --PROMEDIO DEL SALDO DEL BANCO 
 SELECT AVG(SALDO) PROMEDIO_DEL_SALDO_BANCARIO
 FROM CUENTAS;
 

 --CLIENTE CON MAYOR SALDO 
 SELECT MAX(SALDO) AS CLIENTE_MAYOR_SALDO 
 FROM CUENTAS;
 GO

 --CLIENTE CON MAYOR SALDO Y NOMBRE DEL CLIENTE
 SELECT ID_CLIENTE , SALDO
 FROM CUENTAS
 WHERE SALDO = (SELECT MAX(SALDO) FROM CUENTAS)
 GO
 ---CPNTINUACION
 --COMO EL NOMBRE PERTENECE A OTRA TABLA TUVIMOS QUE 
 --HACER INNER JOIN PARA UNIR LAS DOS TABLAS , CLIENTES Y CUENTAS
 SELECT 
		cl.ID_CLIENTE,
		cl.NOMBRES,
		cu.SALDO 
FROM CUENTAS cu
INNER JOIN CLIENTES cl ON cu.ID_CLIENTE = cL.ID_CLIENTE
WHERE cu.SALDO = (SELECT MAX(SALDO) FROM CUENTAS);
GO




 SELECT * FROM CUENTAS
 --CLIENTE CON MENOR SALDO 

 --